-- Enable RLS on all tables
-- Create tables

-- 1. Transactions
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  type text not null check (type in ('income', 'expense')),
  description text not null,
  amount numeric not null,
  date date not null,
  category text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table transactions enable row level security;

create policy "Users can CRUD their own transactions"
  on transactions for all
  using (auth.uid() = user_id);

-- 2. Budget Periods
create table budget_periods (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  start_date date not null,
  end_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table budget_periods enable row level security;

create policy "Users can CRUD their own budget periods"
  on budget_periods for all
  using (auth.uid() = user_id);

-- 3. Budgets
create table budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(), -- Denormalized for easier RLS
  budget_period_id bigint references budget_periods on delete cascade not null,
  category text not null,
  amount numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(budget_period_id, category)
);
alter table budgets enable row level security;

create policy "Users can CRUD their own budgets"
  on budgets for all
  using (auth.uid() = user_id);

-- 4. Settings
create table settings (
  key text primary key,
  user_id uuid references auth.users not null default auth.uid(),
  value text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, key)
);
-- Note: primary key is just 'key' which is problematic for multi-user. 
-- We should make (user_id, key) the primary key or add a surrogate id.
-- Let's drop the primary key constraint on 'key' and make a composite PK.
alter table settings drop constraint settings_pkey;
alter table settings add primary key (user_id, key);

alter table settings enable row level security;

create policy "Users can CRUD their own settings"
  on settings for all
  using (auth.uid() = user_id);
